// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvopupjeorajoarzxobb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2b3B1cGplb3Jham9hcnp4b2JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0ODc5NzYsImV4cCI6MjA2NjA2Mzk3Nn0.go-lVdQJ9ttU7IGOjvzw-QXnnlRdHrnt2S1ehBw7O4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);